/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false workers/bindings.d.ts` (hash: 588138db115cf76c0f02416c32dfddb6)
interface __BaseEnv_Env {
	STATS: D1Database;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
